using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEditor.PackageManager.Requests;
using UnityEngine;

namespace ProjectAegisRTS.UnityClient.EditorTools
{
    public static class Stage3OpenXrSetupReporter
    {
        static readonly string[] RegistryPackages =
        {
            "com.unity.xr.management",
            "com.unity.xr.openxr",
            "com.unity.inputsystem"
        };

        static readonly string[] OptionalPackages =
        {
            "com.unity.xr.interaction.toolkit",
            "com.meta.xr.sdk.core",
            "com.meta.xr.sdk.interaction"
        };

        [MenuItem("ProjectAegisRTS/Report Stage 3 XR Setup Status")]
        public static void ReportMenu()
        {
            Report(false);
        }

        public static void ReportBatch()
        {
            try
            {
                Report(true);
                if (Application.isBatchMode)
                    EditorApplication.Exit(0);
            }
            catch (Exception ex)
            {
                Debug.LogException(ex);
                if (Application.isBatchMode)
                    EditorApplication.Exit(1);
                throw;
            }
        }

        public static void Report(bool attemptSafePackageAdds)
        {
            var repoRoot = GetRepoRoot();
            var docsPath = Path.Combine(repoRoot, "docs");
            Directory.CreateDirectory(docsPath);
            var reportPath = Path.Combine(docsPath, "STAGE3_XR_SETUP_STATUS.md");
            var manifestPath = Path.Combine(GetUnityProjectRoot(), "Packages", "manifest.json");
            var lockPath = Path.Combine(GetUnityProjectRoot(), "Packages", "packages-lock.json");
            var manifest = File.Exists(manifestPath) ? File.ReadAllText(manifestPath) : string.Empty;
            var lockFile = File.Exists(lockPath) ? File.ReadAllText(lockPath) : string.Empty;

            var lines = new List<string>();
            lines.Add("# Stage 3 XR Setup Status");
            lines.Add("");
            lines.Add("Generated by `Stage3OpenXrSetupReporter`.");
            lines.Add("");

            if (attemptSafePackageAdds)
            {
                lines.Add("## Package Add Attempts");
                for (var i = 0; i < RegistryPackages.Length; i++)
                {
                    var packageId = RegistryPackages[i];
                    if (ContainsPackage(manifest, lockFile, packageId))
                    {
                        lines.Add("- `" + packageId + "` already present.");
                        continue;
                    }

                    var result = TryAddPackage(packageId);
                    lines.Add("- `" + packageId + "`: " + result);
                }

                manifest = File.Exists(manifestPath) ? File.ReadAllText(manifestPath) : manifest;
                lockFile = File.Exists(lockPath) ? File.ReadAllText(lockPath) : lockFile;
                lines.Add("");
            }

            lines.Add("## Current Package Status");
            AddPackageStatus(lines, manifest, lockFile, "XR Plug-in Management", "com.unity.xr.management");
            AddPackageStatus(lines, manifest, lockFile, "OpenXR Plugin", "com.unity.xr.openxr");
            AddPackageStatus(lines, manifest, lockFile, "Input System", "com.unity.inputsystem");
            AddPackageStatus(lines, manifest, lockFile, "XR Interaction Toolkit", "com.unity.xr.interaction.toolkit");
            for (var i = 0; i < OptionalPackages.Length; i++)
                if (OptionalPackages[i].StartsWith("com.meta", StringComparison.Ordinal))
                    AddPackageStatus(lines, manifest, lockFile, "Meta XR package", OptionalPackages[i]);

            lines.Add("");
            lines.Add("## Manual Follow-Up");
            lines.Add("- Stage 3 runtime scripts compile without XR packages.");
            lines.Add("- Install/enable OpenXR providers in Project Settings > XR Plug-in Management when headset testing begins.");
            lines.Add("- Add Meta XR Core/Interaction SDK manually from approved sources if Quest hand/controller integrations are needed.");
            lines.Add("- Replace the Stage 3 placeholder rig with XR Origin/XR Interaction Toolkit objects after packages are confirmed.");

            var utf8NoBom = new UTF8Encoding(false);
            File.WriteAllLines(reportPath, lines.ToArray(), utf8NoBom);
            Debug.Log("Stage 3 XR setup status written to " + reportPath);
        }

        static string TryAddPackage(string packageId)
        {
            try
            {
                var request = Client.Add(packageId);
                var deadline = DateTime.UtcNow.AddSeconds(90);
                while (!request.IsCompleted && DateTime.UtcNow < deadline)
                    System.Threading.Thread.Sleep(250);

                if (!request.IsCompleted)
                    return "timed out; package manager may still be resolving.";
                if (request.Status == StatusCode.Success)
                    return "added " + request.Result.packageId + ".";
                return "not added: " + request.Error.message;
            }
            catch (Exception ex)
            {
                return "not added: " + ex.Message;
            }
        }

        static void AddPackageStatus(List<string> lines, string manifest, string lockFile, string label, string packageId)
        {
            var present = ContainsPackage(manifest, lockFile, packageId);
            lines.Add("- " + label + " (`" + packageId + "`): " + (present ? "present" : "not detected"));
        }

        static bool ContainsPackage(string manifest, string lockFile, string packageId)
        {
            return manifest.IndexOf("\"" + packageId + "\"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   lockFile.IndexOf("\"" + packageId + "\"", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        static string GetUnityProjectRoot()
        {
            return Directory.GetParent(Application.dataPath).FullName;
        }

        static string GetRepoRoot()
        {
            return Directory.GetParent(GetUnityProjectRoot()).FullName;
        }
    }
}
