using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace ProjectAegisRTS.UnityClient.EditorTools
{
    public static class Stage4XrSetupReporter
    {
        static readonly string[] PackageIds =
        {
            "com.unity.xr.management",
            "com.unity.xr.openxr",
            "com.unity.inputsystem",
            "com.unity.xr.interaction.toolkit",
            "com.meta.xr.sdk.core",
            "com.meta.xr.sdk.interaction",
            "com.meta.xr.sdk.interaction.ovr"
        };

        [MenuItem("ProjectAegisRTS/Report Stage 4 XR Input Status")]
        public static void ReportMenu()
        {
            Report();
        }

        public static void ReportBatch()
        {
            try
            {
                Report();
                if (Application.isBatchMode)
                    EditorApplication.Exit(0);
            }
            catch (Exception ex)
            {
                Debug.LogException(ex);
                if (Application.isBatchMode)
                    EditorApplication.Exit(1);
                throw;
            }
        }

        public static void Report()
        {
            var repoRoot = GetRepoRoot();
            var docsPath = Path.Combine(repoRoot, "docs");
            Directory.CreateDirectory(docsPath);
            var reportPath = Path.Combine(docsPath, "STAGE4_XR_INPUT_STATUS.md");
            var unityRoot = GetUnityProjectRoot();
            var manifestPath = Path.Combine(unityRoot, "Packages", "manifest.json");
            var lockPath = Path.Combine(unityRoot, "Packages", "packages-lock.json");
            var manifest = File.Exists(manifestPath) ? File.ReadAllText(manifestPath) : string.Empty;
            var lockFile = File.Exists(lockPath) ? File.ReadAllText(lockPath) : string.Empty;

            var lines = new List<string>();
            lines.Add("# Stage 4 XR Input Status");
            lines.Add("");
            lines.Add("Generated by `Stage4XrSetupReporter`.");
            lines.Add("");
            lines.Add("## Current Package Status");
            AddPackageStatus(lines, manifest, lockFile, "XR Plug-in Management", "com.unity.xr.management");
            AddPackageStatus(lines, manifest, lockFile, "OpenXR Plugin", "com.unity.xr.openxr");
            AddPackageStatus(lines, manifest, lockFile, "Input System", "com.unity.inputsystem");
            AddPackageStatus(lines, manifest, lockFile, "XR Interaction Toolkit", "com.unity.xr.interaction.toolkit");
            AddPackageStatus(lines, manifest, lockFile, "Meta XR Core SDK", "com.meta.xr.sdk.core");
            AddPackageStatus(lines, manifest, lockFile, "Meta XR Interaction SDK", "com.meta.xr.sdk.interaction");
            AddPackageStatus(lines, manifest, lockFile, "Meta XR Interaction OVR", "com.meta.xr.sdk.interaction.ovr");
            lines.Add("");
            lines.Add("## Stage 4 Adapter Status");
            lines.Add("- `DesktopLeftHandInputSource` drives the left-hand UI without a headset.");
            lines.Add("- `XrLeftHandInputAdapter` is compile-safe and currently no-op unless a left ray origin is assigned and enabled.");
            lines.Add("- No Meta or XR Interaction Toolkit types are hard-referenced by Stage 4 runtime scripts.");
            lines.Add("");
            lines.Add("## Recommended Manual Quest Setup");
            lines.Add("- Keep the Stage 4 scene working with desktop fallback before connecting hardware input.");
            lines.Add("- Install Meta XR Core SDK and Meta XR Interaction SDK manually from approved sources.");
            lines.Add("- Add an XR Origin and connect its left controller or hand ray transform to `XrLeftHandInputAdapter.leftRayOrigin`.");
            lines.Add("- Map trigger/select, grip/modifier, thumbstick category axis, and hand pinch in the adapter behind package-specific compile guards.");
            lines.Add("- Test on Quest 3S after OpenXR provider settings and Android build target are configured.");
            lines.Add("");
            lines.Add("## Package IDs Checked");
            for (var i = 0; i < PackageIds.Length; i++)
                lines.Add("- `" + PackageIds[i] + "`");

            File.WriteAllLines(reportPath, lines.ToArray(), new UTF8Encoding(false));
            Debug.Log("Stage 4 XR input status written to " + reportPath);
        }

        static void AddPackageStatus(List<string> lines, string manifest, string lockFile, string label, string packageId)
        {
            var present = ContainsPackage(manifest, lockFile, packageId);
            lines.Add("- " + label + " (`" + packageId + "`): " + (present ? "present" : "not detected"));
        }

        static bool ContainsPackage(string manifest, string lockFile, string packageId)
        {
            return manifest.IndexOf("\"" + packageId + "\"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   lockFile.IndexOf("\"" + packageId + "\"", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        static string GetUnityProjectRoot()
        {
            return Directory.GetParent(Application.dataPath).FullName;
        }

        static string GetRepoRoot()
        {
            return Directory.GetParent(GetUnityProjectRoot()).FullName;
        }
    }
}
